import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TabManager } from "@/components/TabManager";
import { Logo } from "@/components/Logo";
import { FloatButton } from "antd";
import { FaArrowUp  } from "react-icons/fa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Adri & Bri",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased select-none`}
      >
        <link rel="icon" href="/images/logo.ico" />
        <div id="top"></div>
        <Logo ></Logo>
        <br />
        <div className="grid grid-cols-12 gap-4">
          <div className="col-span-10 col-start-2">
            <TabManager></TabManager>
            <div id="mainContainer" className="container shadow-md shadow-[#FF8FA3] mb-10 bg-white rounded-md">
              {children}
            </div>
            <FloatButton icon={<FaArrowUp  />} tooltip={<div>Volver Arriba</div>} className="bg-[#8F0700]" href="#top"/>
          </div>
        </div>
      </body>
    </html>
  );
}
